/*
  ============================================================
  EDIT THIS FILE TO ADD, REMOVE OR CHANGE YOUR WISHLIST ITEMS
  ============================================================

  Copy one full item block, paste it below, then change its details.

  wishlist:
  - Give each item a list name, such as "General", "Birthday" or "Christmas".
  - The website will automatically create a filter for every list name used.

  brand:
  - Enter the product brand, such as "Gigabyte", "UGREEN" or "Tapo".

  notes:
  - Add any extra reminder or personal note.
  - Leave it blank ("") if you do not need a note.

  image:
  - Use a direct image URL, for example: "https://example.com/photo.jpg"
  - Or add an image to an "images" folder and use: "images/photo.jpg"
  - Leave it blank ("") to show a stylish letter placeholder.

  price:
  - Enter numbers only. Example: 79.99

  quantity:
  - Enter how many of the item you want. Example: 2
  - Use a whole number between 1 and 99.

  priority:
  - Use "High", "Medium" or "Low"

  purchased:
  - Use true if bought, or false if still wanted.
*/

const wishlistItems = [
  {
    name: "Gigabyte GS32QCA 31.5 QHD Curved Gaming Monitor",
    wishlist: "Gaming",
    category: "Technology",
    brand: "Gigabyte",
    price: 199,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "Currys",
    dateAdded: "2026-07-26",
    image: "https://media.currys.biz/i/currysprod/10282565?$l-large$&fmt=auto",
    link: "https://www.currys.co.uk/products/gigabyte-gs32qca-quad-hd-31.5-curved-va-lcd-gaming-monitor-black-10282565.html?searchTerm=gigabyte%2031.5",
    description: "Gaming Monitor to replace BUSH TV.",
    notes: ""
  },
  {
    name: "Tapo L530B Smart Bulb B22",
    wishlist: "General",
    category: "Lighting",
    brand: "Tapo",
    price: 7.99,
    quantity: 1,
    priority: "Low",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-24",
    image: "https://m.media-amazon.com/images/I/71BBEvO36ML._AC_SL1500_.jpg",
    link: "https://www.amazon.co.uk/TP-LINK-Tapo-Colour-Changeable-Required-L530B/dp/B08JZHXQC4",
    description: "Light Bulb",
    notes: ""
  },
  {
    name: "Wooden Phone Docking Station & Desk Organiser",
    wishlist: "General",
    category: "Home",
    brand: "",
    price: 20.16,
    quantity: 1,
    priority: "Low",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/71T+tFXj5OL._AC_SL1500_.jpg",
    link: "https://www.amazon.co.uk/gp/aw/d/B0B2P429BZ",
    description: "Black wooden docking station for organising a phone, watch, wallet, keys and other everyday items.",
    notes: ""
  },
  {
    name: "IVANKY VESA Certified DisplayPort Cable 2m",
    wishlist: "Gaming",
    category: "Accessories",
    brand: "IVANKY",
    price: 5.99,
    quantity: 3,
    priority: "High",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/415hJKWbacL.jpg",
    link: "https://www.amazon.co.uk/gp/aw/d/B07JQKWX3C",
    description: "Two-metre braided DisplayPort cable for connecting a gaming PC or graphics card to a monitor.",
    notes: "Need to be bought with Monitors"
  },
  {
    name: "UGREEN Cat 6 Braided Ethernet Cable 1m",
    wishlist: "Gaming",
    category: "Accessories",
    brand: "UGREEN",
    price: 4.20,
    quantity: 3,
    priority: "Medium",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/71Sg0qkGY2L._AC_SL1500_.jpg",
    link: "https://www.amazon.co.uk/gp/aw/d/B086H8KM61",
    description: "One-metre braided Cat 6 Ethernet cable for a PC, games console, television, router or network switch.",
    notes: ""
  },
  {
    name: "Corsair RM850e 850W Fully Modular Power Supply",
    wishlist: "Gaming",
    category: "Technology",
    brand: "Corsair",
    price: 127.99,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "Currys",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/71UlVM3qc5L._AC_SL1500_.jpg",
    link: "https://www.currys.co.uk/products/corsair-lownoise-rm850e-modular-atx-psu-850-w-10275775.html?searchTerm=Corsair%20RM850e",
    description: "850W fully modular, low-noise ATX power supply for upgrading a gaming PC.",
    notes: "Need to be bought with or at the same time as Graphics Card"
  },
  {
    name: "Gigabyte GS25F2A 24.5-inch Full HD Gaming Monitor",
    wishlist: "Gaming",
    category: "Technology",
    brand: "Gigabyte",
    price: 99,
    quantity: 2,
    priority: "High",
    purchased: false,
    store: "Currys",
    dateAdded: "2026-07-26",
    image: "https://media.currys.biz/i/currysprod/10299628?$l-large$&fmt=auto",
    link: "https://www.currys.co.uk/products/gigabyte-gs25f2a-full-hd-24.5-ips-lcd-gaming-monitor-black-10299628.html",
    description: "24.5-inch Full HD IPS gaming monitor with a 240Hz refresh rate, 1ms response time, built-in speakers and VESA mounting support.",
    notes: ""
  },
    {
    name: "UGREEN 5 Port Gigabit Network Switch, Ethernet Splitter Hub",
    wishlist: "Gaming",
    category: "Accessories",
    brand: "UGREEN",
    price: 9.99,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/71LDan+M0QL._AC_SL1500_.jpg",
    link: "https://www.amazon.co.uk/UGREEN-Ethernet-Splitter-High-speed-Wall-Mounting/dp/B0D9GRJ1H8/ref=sr_1_5?crid=7MLSCJHBJ02I&dib=eyJ2IjoiMSJ9.Vsjl1l-Y30xIGqbEOqQUIVQhzgLx6ccr6_xaz875Hko.HIipWd9FqaBmQSI_cO628s7Zd1eupoRkEiUZEs97WIw&dib_tag=se&keywords=ugreen%2B5%2Bmegabit%2Bport&qid=1785064196&sprefix=ugreen%2B5%2Bmegabit%2Bport%2Caps%2C230&sr=8-5&th=1",
    description: "",
    notes: "Needs Ethernet's and WiFi Extender"
  },
      {
    name: "Trust Yuri 2.1 Speaker Set with Wooden Subwoofer",
    wishlist: "Gaming",
    category: "Technology",
    brand: "Trust",
    price: 49.99,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/71zXBFY6t+L._AC_SL1500_.jpg",
    link: "https://www.amazon.co.uk/Trust-Subwoofer-Speakers-Headphones-Connections/dp/B08FR5T7N5/ref=sr_1_1?crid=1OSM4GGKRHRFN&dib=eyJ2IjoiMSJ9.GFwRTtvj3Sp1luGwzU8p2KcQS5-gL2H2H8_r-iyGa-RpR9ioD1HY-sBFQ0-vi1SEUXq5YFDeaCckJIx_iJxWsA.mQWZycz9yEK9HmnDPVtEWqEuzAIS1VnHsZ8I0VTs7QQ&dib_tag=se&keywords=Trust+Yuri+2.1&qid=1785064387&sprefix=trust+yuri+2.1%2Caps%2C193&sr=8-1&ufe=app_do%3Aamzn1.fos.95fd378e-6299-4723-b1f1-3952ffba15af",
    description: "PC Speakers with Subwoofer",
    notes: ""
  },
        {
    name: "UGREEN Extension Lead 1.5M, 6 Way Power Strip with 3 USB-A & 1 USB-C",
    wishlist: "Gaming",
    category: "Accessories",
    brand: "UGREEN",
    price: 16.99,
    quantity: 2,
    priority: "Medium",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/617DdqPuTzL._AC_SL1500_.jpg",
    link: "https://www.amazon.co.uk/UGREEN-Extension-Cord-Socket-Black/dp/B0FKBH9HWN/ref=sr_1_6?crid=2SG3FU26L107G&dib=eyJ2IjoiMSJ9.2WPnN9YpVOwHl2zF0jvfXANm8AKkirvSB9ElxK2wqD12Di6q1v0OxHQibH8qO70Y8CJWGtOLfe_csCYwI08aAxQnV79OMUKQZf_qdv94sT9nXsPD1l2LmGmR9Zr2-bOLmNjm4igsDUwsw-96-YoYx-XFfFLoPgam0OzeU54PStaShnF9fbW4vKEftIjgEoOPQSfTQx3SKcYmtKI-y3CGJ6mOvCyb3TLYAdyLLMnVFSRBg9AD0DTWOR0qGJIT6r7hm0M-WJ4FpcDyq4wtA_mNOwrGiM-lkHZ9e-G-BDk5fZM.r1AcsXB68oqkIlQzn9SddcnKbPeMJlopOgqftxGLXjs&dib_tag=se&keywords=ugreen+extension+lead&qid=1785064637&sprefix=ugreen+ex%2Caps%2C222&sr=8-6",
    description: "UGREEN Extension Lead with Ports",
    notes: ""
  },
          {
    name: "ULTIMEA 2.1ch Soundbar",
    wishlist: "General",
    category: "Technology",
    brand: "ULTIMEA",
    price: 49.99,
    quantity: 1,
    priority: "Medium",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/61kFlKGxwzL._AC_AA180_.jpg",
    link: "https://www.amazon.co.uk/gp/product/B0G69M2QYZ/ref=ox_sc_act_title_11?smid=A3PO8DYFHHRUSO&psc=1",
    description: "TV Soundbar",
    notes: ""
  },
          {
    name: "Ultrawide Monitor Arm for 17-49 Inch Screens",
    wishlist: "Gaming",
    category: "Accessories",
    brand: "",
    price: 29.99,
    quantity: 1,
    priority: "Medium",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/61bKqAr8hoL._AC_AA180_.jpg",
    link: "https://www.amazon.co.uk/gp/product/B0DYP7CDCH/ref=ox_sc_act_title_12?smid=A222U3U251U7TA&psc=1",
    description: "Monitor Arm for Curved Monitor",
    notes: ""
  }, 
          {
    name: "MOUNTUP Dual Monitor Arm Desk Mount for 13–32 Inch Screens",
    wishlist: "Gaming",
    category: "Accessories",
    brand: "",
    price: 23.99,
    quantity: 1,
    priority: "Medium",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/61ZCBQ5YAtL._AC_SY300_SX300_QL70_ML2_.jpg",
    link: "https://www.amazon.co.uk/gp/product/B07ZNRNT3C/ref=ox_sc_act_title_13?smid=A3CXTSOTCRTJYX&psc=1",
    description: "Dual Monitor Arm ",
    notes: ""
  },  
          {
    name: "UGREEN HDMI Switch 4K@60Hz Bi-directional HDMI Splitter 2 In 1 Out",
    wishlist: "Gaming",
    category: "Technology",
    brand: "UGREEN",
    price: 9.99,
    quantity: 1,
    priority: "Medium",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/61Ps7-9TExL._AC_SY300_SX300_QL70_ML2_.jpg",
    link: "https://www.amazon.co.uk/gp/product/B07H7JCCKM/ref=ox_sc_act_title_14?smid=AXZ3JQ1GVFPIF&psc=1",
    description: "HDMI Splitter",
    notes: ""
  },    
          {
    name: "Tapo TP-Link Smart Bulb, Smart WiFi LED Light, E27",
    wishlist: "Gaming",
    category: "Technology",
    brand: "Tapo",
    price: 7.99,
    quantity: 1,
    priority: "Medium",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-26",
    image: "https://m.media-amazon.com/images/I/61OcfOujjlL._AC_AA180_.jpg",
    link: "https://www.amazon.co.uk/gp/product/B08GKYYK7X/ref=ox_sc_act_title_15?smid=A3P5ROKL5A1OLE&psc=1",
    description: "Light Bulb",
    notes: ""
  }, 
          {
    name: "GIGABYTE GeForce RTX 5060 8 GB EAGLE OC Graphics Card",
    wishlist: "Gaming",
    category: "Technology",
    brand: "GIGABYTE",
    price: 309.99,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "Currys",
    dateAdded: "2026-07-26",
    image: "https://media.currys.biz/i/currysprod/10275089?$l-large$&fmt=auto",
    link: "https://www.currys.co.uk/products/gigabyte-geforce-rtx-5060-8-gb-eagle-oc-graphics-card-10275089.html",
    description: "Light Bulb",
    notes: ""
  },
          {
    name: "MALM Bed frame, high, dark grey/Luröy, Standard Double",
    wishlist: "Bedroom",
    category: "Furniture",
    brand: "IKEA",
    price: 179,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "IKEA",
    dateAdded: "2026-07-26",
    image: "https://www.ikea.com/gb/en/images/products/malm-bed-frame-high-dark-grey-luroey__1392603_pe966167_s5.jpg?f=s",
    link: "https://www.ikea.com/gb/en/p/malm-bed-frame-high-dark-grey-luroey-s19589995/#content",
    description: "",
    notes: "Dark Grey"
  },   
          {
    name: "VESTERÖY Pocket sprung mattress, medium firm/light blue, Standard Double",
    wishlist: "Bedroom",
    category: "Furniture",
    brand: "IKEA",
    price: 199,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "IKEA",
    dateAdded: "2026-07-26",
    image: "https://www.ikea.com/gb/en/images/products/vesteroey-pocket-sprung-mattress-medium-firm-light-blue__1150852_pe884907_s5.jpg?f=s",
    link: "https://www.ikea.com/gb/en/p/vesteroey-pocket-sprung-mattress-medium-firm-light-blue-80450635/",
    description: "",
    notes: "Medium Firm"
  }, 
          {
    name: "KNARREVIK Bedside table, black, 42x34x52 cm",
    wishlist: "Bedroom",
    category: "Furniture",
    brand: "IKEA",
    price: 12,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "IKEA",
    dateAdded: "2026-07-26",
    image: "https://www.ikea.com/gb/en/images/products/knarrevik-bedside-table-black__1255278_pe924478_s5.jpg?f=s",
    link: "https://www.ikea.com/gb/en/p/knarrevik-bedside-table-black-20569977/",
    description: "",
    notes: ""
  },  
          {
    name: "LACK Wall shelf, black-brown, 110x26 cm",
    wishlist: "Bedroom",
    category: "Furniture",
    brand: "IKEA",
    price: 15,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "IKEA",
    dateAdded: "2026-07-26",
    image: "https://www.ikea.com/gb/en/images/products/lack-wall-shelf-black-brown__0641085_pe700249_s5.jpg?f=s",
    link: "https://www.ikea.com/gb/en/p/lack-wall-shelf-black-brown-40103633/#content",
    description: "",
    notes: ""
  }, 
          {
    name: "ALEX Drawer unit, dark grey, 36x70 cm",
    wishlist: "Bedroom",
    category: "Furniture",
    brand: "IKEA",
    price: 70,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "IKEA",
    dateAdded: "2026-07-26",
    image: "https://www.ikea.com/gb/en/images/products/alex-drawer-unit-dark-grey__1411364_pe973103_s5.jpg?f=s",
    link: "https://www.ikea.com/gb/en/p/alex-drawer-unit-dark-grey-60588894/#content",
    description: "",
    notes: "1/3 Parts for TV Unit"
  }, 
            {
    name: "ALEX Storage unit, dark grey, 36x70 cm",
    wishlist: "Bedroom",
    category: "Furniture",
    brand: "IKEA",
    price: 45,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "IKEA",
    dateAdded: "2026-07-26",
    image: "https://www.ikea.com/gb/en/images/products/alex-storage-unit-dark-grey__1411365_pe973104_s5.jpg?f=s",
    link: "https://www.ikea.com/gb/en/p/alex-storage-unit-dark-grey-70588898/#content",
    description: "",
    notes: "2/3 Parts for TV Unit"
  },   
            {
    name: "LINNMON Table top, white stained oak effect, 100x60 cm",
    wishlist: "Bedroom",
    category: "Furniture",
    brand: "IKEA",
    price: 15,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "IKEA",
    dateAdded: "2026-07-26",
    image: "https://www.ikea.com/gb/en/images/products/linnmon-table-top-white-stained-oak-effect__0989117_pe818385_s5.jpg?f=s",
    link: "https://www.ikea.com/gb/en/p/linnmon-table-top-white-stained-oak-effect-70473604/#contentt",
    description: "",
    notes: "3/3 Parts for TV Unit"
  },    
            {
    name: "Essential Elasticated Waist Black Slim Fit Cargo Shorts",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "boohooMAN",
    price: 20,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "BoohooMAN",
    dateAdded: "2026-07-26",
    image: "https://mediahub.boohooman.com/cmm04063_black_xl?qlt=70&w=549&ssz=true&dpr=1",
    link: "https://www.boohooman.com/product/boohooman-essential-elasticated-waist-black-slim-fit-cargo-shorts_cmm04063?colour=black",
    description: "",
    notes: "Black and in Large. Usually on Sale."
  },
            {
    name: "White Oversized Interlock Monaco Car Print T-Shirt",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "boohooMAN",
    price: 16,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "boohooMAN",
    dateAdded: "2026-07-26",
    image: "https://mediahub.boohooman.com/cmm26949_white_xl?qlt=70&w=549&ssz=true&dpr=1",
    link: "https://www.boohooman.com/product/boohooman-white-oversized-interlock-monaco-car-print-t-shirt_cmm26949?colour=white",
    description: "",
    notes: "Usually on Sale."
  }, 
            {
    name: "White Oversized Monaco Racing Print T-Shirt",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "boohooMAN",
    price: 18,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "boohooMAN",
    dateAdded: "2026-07-26",
    image: "https://mediahub.boohooman.com/cmm26528_white_xl?qlt=70&w=549&ssz=true&dpr=1",
    link: "https://www.boohooman.com/product/boohooman-white-oversized-monaco-racing-print-t-shirt_cmm26528?colour=white",
    description: "",
    notes: "Usually on Sale."
  },  
            {
    name: "Essential Relaxed Fit Short",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "boohooMAN",
    price: 16,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "boohooMAN",
    dateAdded: "2026-07-26",
    image: "https://mediahub.boohooman.com/cmm22682_black_xl?qlt=70&w=549&ssz=true&dpr=1",
    link: "https://www.boohooman.com/product/boohooman-essential-relaxed-fit-short_cmm22682?colour=black",
    description: "",
    notes: "Usually on Sale."
  }, 
            {
    name: "Essential Baggy Fit Elasticated Twill Cargo Shorts",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "boohooMAN",
    price: 18,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "boohooMAN",
    dateAdded: "2026-07-26",
    image: "https://mediahub.boohooman.com/cmm24454_grey_xl?qlt=70&w=549&ssz=true&dpr=1",
    link: "https://www.boohooman.com/product/boohooman-essential-baggy-fit-elasticated-twill-cargo-shorts_cmm24454?colour=grey",
    description: "",
    notes: "Usually on Sale."
  },  
            {
    name: "Regular Fit 2 Pack Essential Crew Neck T-Shirts",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "boohooMAN",
    price: 15,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "boohooMAN",
    dateAdded: "2026-07-26",
    image: "https://mediahub.boohooman.com/cmm26048_mono_xl?qlt=70&w=549&ssz=true&dpr=1",
    link: "https://www.boohooman.com/product/boohooman-regular-fit-2-pack-essential-crew-neck-t-shirts_cmm26048?colour=mono",
    description: "",
    notes: "Usually on Sale."
  }, 
            {
    name: "Oversized Lightening McQueen License Print T-Shirt",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "boohooMAN",
    price: 20,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "boohooMAN",
    dateAdded: "2026-07-26",
    image: "https://mediahub.boohooman.com/cmm31086_black_xl?qlt=70&w=549&ssz=true&dpr=1",
    link: "https://www.boohooman.com/product/boohooman-oversized-lightening-mcqueen-license-print-t-shirt_cmm31086?colour=black",
    description: "",
    notes: "Usually on Sale."
  }, 
            {
    name: "APPLE MacBook Air 13.6 (2026) - M5, 512 GB SSD, RAM 16 GB, Midnight",
    wishlist: "General",
    category: "Technology",
    brand: "Apple",
    price: 1299,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "Currys",
    dateAdded: "2026-07-26",
    image: "https://media.currys.biz/i/currysprod/10292806?$l-large$&fmt=auto",
    link: "https://www.currys.co.uk/products/apple-macbook-air-13.6-2026-m5-512-gb-ssd-ram-16-gb-midnight-10292806.html",
    description: "",
    notes: ""
  },   
            {
    name: "Air Force 1 Low",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 110,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "JD Sports",
    dateAdded: "2026-07-26",
    image: "https://i8.amplience.net/i/jpl/jd_751993_b?$prod404enGB$&qlt=default&fmt=auto&w=589&h=418",
    link: "https://www.jdsports.co.uk/product/white-nike-air-force-1-low/19685420/?cm_mmc=googleshop-_-google-_-shopping-_-pla&applink=1&gad_source=1&gad_campaignid=23602599060&gclid=CjwKCAjwpqHTBhAcEiwAj2AfusvbzOxzUHX45jvfBTiVV-91dHxnLLf9uGvRA3BIJ4xckjruQ8B8MhoCEyUQAvD_BwE",
    description: "",
    notes: ""
  },  
             {
    name: "Air Force 1 Low",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 85,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "Foot Locker",
    dateAdded: "2026-07-26",
    image: "https://assets.footlocker.com/is/image/FLDM/314109070004_01?fmt=webp-alpha&bfc=on&wid=500&hei=500",
    link: "https://www.footlocker.co.uk/en/product/~/314109070004.html?channable=03fda0696400333134313039303730303034313030f6&utm_source=google&utm_medium=cpc&utm_campaign=_1%3Auk_2%3Aperformance_3%3Agoogle_4%3Ado_5%3Ashopping_6%3Aconversion_7%3Amix_8%3Aalways%20on_9%3Amultiple_10%3Ana_16%3Abranded&utm_id=19541007735&gad_source=1&gad_campaignid=19541007735&gclid=CjwKCAjwpqHTBhAcEiwAj2AfugkQCeklEweNWzhQU8MpUlrzyxzvpOhB4Yrs0mOvrdFOx2Gb4OeQWRoC6GAQAvD_BwE",
    description: "",
    notes: ""
  },   
            {
    name: "Air Force 1 Low",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 110,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "JD Sports",
    dateAdded: "2026-07-26",
    image: "https://i8.amplience.net/i/jpl/jd_030664_a?$prod404enGB$&qlt=default&fmt=auto&w=589&h=418",
    link: "https://www.jdsports.co.uk/product/white-nike-air-force-1-low/1267679/",
    description: "",
    notes: ""
  },
              {
    name: "Air Force 1 Low",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 110,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "JD Sports",
    dateAdded: "2026-07-26",
    image: "https://i8.amplience.net/i/jpl/jd_047951_b?$prod404enGB$&qlt=default&fmt=auto&w=589&h=418",
    link: "https://www.jdsports.co.uk/product/black-nike-air-force-1-low/047951/",
    description: "",
    notes: ""
  },
                {
    name: "Nike Core T-Shirt",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 23,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "JD Sports",
    dateAdded: "2026-07-26",
    image: "https://i8.amplience.net/i/jpl/jd_764258_a?$prod404enGB$&qlt=default&fmt=auto&w=589&h=752",
    link: "https://www.jdsports.co.uk/product/white-nike-core-t-shirt/19697698/",
    description: "",
    notes: ""
  }, 
                {
    name: "Nike Core T-Shirt",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 23,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "JD Sports",
    dateAdded: "2026-07-26",
    image: "https://i8.amplience.net/i/jpl/jd_708680_a?$prod404enGB$&qlt=default&fmt=auto&w=589&h=752",
    link: "https://www.jdsports.co.uk/product/black-nike-core-t-shirt/19650643/",
    description: "",
    notes: ""
  },  
              {
    name: "Air Force 1 Low",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 120,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "JD Sports",
    dateAdded: "2026-07-26",
    image: "https://i8.amplience.net/i/jpl/jd_800312_b?$prod404enGB$&qlt=default&fmt=auto&w=589&h=418",
    link: "https://www.jdsports.co.uk/product/nike-air-force-1-low/19755346/",
    description: "",
    notes: ""
  },  
              {
    name: "Tech Mix T-Shirt",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 35,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "JD Sports",
    dateAdded: "2026-07-26",
    image: "https://i8.amplience.net/i/jpl/jd_791115_a?$prod404enGB$&qlt=default&fmt=auto&w=589&h=752",
    link: "https://www.jdsports.co.uk/product/black-nike-tech-mix-t-shirt/19739648/",
    description: "",
    notes: ""
  },   
                {
    name: "Nike Core T-Shirt",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 23,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "JD Sports",
    dateAdded: "2026-07-26",
    image: "https://i8.amplience.net/i/jpl/jd_780042_b?$prod404enGB$&qlt=default&fmt=auto&w=589&h=752",
    link: "https://www.jdsports.co.uk/product/grey-nike-core-t-shirt/19738750/",
    description: "",
    notes: ""
  }, 
               {
    name: "Tech Mix Shorts",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 65,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "JD Sports",
    dateAdded: "2026-07-26",
    image: "https://i8.amplience.net/i/jpl/jd_791116_a?$prod404enGB$&qlt=default&fmt=auto&w=589&h=752",
    link: "https://www.jdsports.co.uk/product/black-nike-tech-mix-shorts/19744922/",
    description: "",
    notes: ""
  },
               {
    name: "Foundation Shorts",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 25,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "JD Sports",
    dateAdded: "2026-07-26",
    image: "https://i8.amplience.net/i/jpl/jd_788870_b?$prod404enGB$&qlt=default&fmt=auto&w=589&h=752",
    link: "https://www.jdsports.co.uk/product/grey-nike-foundation-shorts/19749011/?cm_mmc=googleshop-_-google-_-shopping-_-pla&applink=1&gad_source=1&gad_campaignid=23602599060&gclid=CjwKCAjwpqHTBhAcEiwAj2AfujRSkFrjXNICErcbc0m0lwMnVix9VEKRqyd0-IbWoP_SsaDtfoDNdhoCg6UQAvD_BwE",
    description: "",
    notes: ""
  }, 
               {
    name: "Woven Cargo Shorts",
    wishlist: "Clothing",
    category: "Clothing",
    brand: "Nike",
    price: 45,
    quantity: 1,
    priority: "High",
    purchased: false,
    store: "JD Sports",
    dateAdded: "2026-07-26",
    image: "https://i8.amplience.net/i/jpl/jd_761404_b?$prod404enGB$&qlt=default&fmt=auto&w=589&h=752",
    link: "https://www.jdsports.co.uk/product/black-nike-woven-cargo-shorts/19693760/",
    description: "",
    notes: ""
  },   
                {
    name: "SONY PlayStation 5 Digital Edition",
    wishlist: "Gaming",
    category: "Technology",
    brand: "Sony",
    price: 519,
    quantity: 1,
    priority: "Low",
    purchased: false,
    store: "Currys",
    dateAdded: "2026-07-31",
    image: "https://media.currys.biz/i/currysprod/10291988?$l-large$&fmt=auto",
    link: "https://www.currys.co.uk/products/sony-playstation-5-digital-edition-10291988.html?searchTerm=PS5",
    description: "",
    notes: ""
  }, 
                  {
    name: "OIVO PS5/Slim/Pro Stand and Cooling Station",
    wishlist: "Gaming",
    category: "Technology",
    brand: "",
    price: 26.99,
    quantity: 1,
    priority: "Low",
    purchased: false,
    store: "Amazon",
    dateAdded: "2026-07-31",
    image: "https://m.media-amazon.com/images/I/713asLPZglL._AC_SL1500_.jpg",
    link: "https://www.amazon.co.uk/OIVO-Controller-Charging-Playstation-Upgraded-White/dp/B08T1KHHR9/ref=sr_1_5?crid=1GIMA3F2CT9YV&dib=eyJ2IjoiMSJ9.1abQ98o4mNULwDxRhELgh5aZ-l-flC9eRJiPQvQE84bs7UgihHyPbbdWkQwBnb2dKQAsKYQEl_HfekSDi2oB7saHpj1zBzuJHlRyeX2gtsToW1_EYC_96OQZjzCVmt7Qm_KXmU3sayyDtPVdQWFmMT8y6wTwUqT7LuB-PyRIiRp137T5z0D6McXpp4t0SLba-Q0Bmi1aWeB4tsG_NuTUmACulmTWIS45BnLC8P5Kb0A.fczW1BiKSneBdNp7Tw0HZnAjleyDok62P-ST1Rb4kxU&dib_tag=se&keywords=ps5%2Baccessories&qid=1785491982&sprefix=PS5%2Bac%2Caps%2C345&sr=8-5&th=1",
    description: "",
    notes: "Only to be bought with or after PS5."
  },
                  {
    name: "RAZER TAROK PRO X Cloth Gaming Chair - Grey & Green",
    wishlist: "Gaming",
    category: "Furniture",
    brand: "RAZER",
    price: 249,
    quantity: 1,
    priority: "Low",
    purchased: false,
    store: "Currys",
    dateAdded: "2026-07-31",
    image: "https://media.currys.biz/i/currysprod/10238929?$l-large$&fmt=auto",
    link: "https://www.currys.co.uk/products/razer-tarok-pro-x-cloth-gaming-chair-grey-and-green-10238929.html",
    description: "",
    notes: "Sometimes on Sale"
  },  
];
